name: Recipe App

on:
    push:
        branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Home.py test
        env:
          TESTING: 1
        run: |
          PYTHONPATH=$PWD pytest tests/


